import { Inter } from "next/font/google";
import { AuthProvider } from "./(context)/auth";
import ThemeProvider from "./(component)/ThemeProvider/themeProvider";
import BodyClassManager from "./(component)/ThemeProvider/BodyClassManager";
import "./globals.css";
import CheckAuth from "./(actions)/CheckAuth/CheckAuth";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Blank Web",
    description: "Generated by create next app"
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <AuthProvider>
                    <CheckAuth>
                        <ThemeProvider>
                            <BodyClassManager />
                            {children}
                        </ThemeProvider>
                    </CheckAuth>
                </AuthProvider>
            </body>
        </html>
    );
}
