import { Inter } from "next/font/google";
import { AuthProvider } from "./(context)/auth";
import "@/app/globals.css";
import CheckAuth from "./(actions)/CheckAuth/CheckAuth";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Blank Web",
    description: "Generated by create next app"
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <AuthProvider>
                    <CheckAuth>{children}</CheckAuth>
                </AuthProvider>
            </body>
        </html>
    );
}
